KEYWORDS = {
    "Application": "Papers that demonstrate practical uses of 3DSGs beyond their construction.",
    "Manipulation": "Papers that leverage 3DSGs to support object manipulation tasks.",
    "Navigation": "Papers that leverage 3DSGs to support navigation tasks.",
    "Planning": "Papers that leverage 3DSGs to support planning tasks.",
    "XR": "Papers that connect XR interfaces with 3DSGs for immersive interaction and editing.",
    "LLM": "Papers that integrate 3DSGs with LLMs for downstream tasks.",
    "SUN": "Papers that leverage 3DSGs to perform scene understanding tasks.",
    "Policy": "Papers that leverage 3DSGs to perform policy learning.",
    "Multi-Robot": "Papers that consider 3DSGs in multi-robot collaboration.",
    "Outdoor": "Papers that study 3DSGs in outdoor environments.",
    "Indoor": "Papers that study 3DSGs in indoor environments.",
    "Active": "Papers that build or update the graph through active interaction or perception.",
    "Short-Term Dynamics": "Papers that ensure short-term temporal consistency, capturing updates and tracking dynamic entities.",
    "Long-Term Dynamics": "Papers that capture long-term scene changes, focusing on the results of updates.",
    "Compression": "Papers that maintain lightweight representations of the scene through compression.",
    "Hierarchical": "Papers that organize the graph hierarchically.",
    "Incremental": "Papers that process input incrementally, updating the graph as data arrives.",
    "Real-Time": "Papers that perform incremental, on-device computation at sensor rate to enable real-time scene graph construction and updates.",
    "Dataset": "Papers that introduce datasets for building or evaluating 3DSGs.",
    "Pre-Built PCD": "Papers that leverage pre-built point cloud datasets for 3DSG construction.",
    "RGB-D": "Papers that rely on RGB-D data for building 3DSGs.",
    "LiDAR": "Papers that rely on LiDAR data for building 3DSGs.",
    "SLAM": "Papers that couple 3DSG construction with SLAM to account for spatial uncertainty and ensure global consistency.",
    "Open-Vocabulary": "Papers that adopt open-vocabulary approaches for flexible scene understanding.",
    "Humans": "Papers that model humans in the scene, including their trajectories and interactions with the environment.",
}

FIELDS = [
    "TITLE",
    "VENUE",
    "DATE",
    "AUTHOR",
    "ABSTRACT",
    "ARXIV",
    "BIBTEX_KEY",
    "FIRSTINSTITUTE",
    "KEYWORD",
    "SITE",
    "CODE",
    "VIDEO",
]

VENUES = {
    "3dim": "Intl. Conf. on 3D Digital Imaging and Modeling",
    "3dv": "Intl. Conf. on 3D Vision (3DV)",
    "3dpvt": "3D Data Processing Visualization and Transmission (3DPVT)",
    "aaai": "AAAI Conf. on Artificial Intelligence (AAAI)",
    "aamas": "Intl. Conf. on Autonomous Agents and Multi-Agent Systems (AAMAS)",
    "ac": "IEEE Aerospace Conference",
    "acc": "American Control Conference",
    "access": "{IEEE Access}",
    "accv": "Asian Conf. on Computer Vision (ACCV)",
    "acl": "Association for Computational Linguistics (ACL)",
    "acmcs": "ACM Computing Surveys",
    "acmuist": "ACM Symp. on User interface software and technology",
    "acmsig": "ACM Symp. Geom. Process.",
    "acmsuist": "ACM Symp. on User Interface Software and Technology",
    "acra": "Australasian Conf. on Robotics and Automation (ACRA)",
    "addison": "Addison-Wesley Publishing",
    "advcgh": "Advances in Computer Graphics Hardware IV",
    "advrobotics": "Advanced Robotics",
    "adveng": "Advanced Engineering Informatics",
    "aes": "IEEE Trans. Aerosp. Electron. Syst.",
    "agsys": "Agricultural Systems",
    "ai": "Artificial Intelligence",
    "aicv94": "Application of Invariance in Computer Vision",
    "aim": "IEEE/ASME Intl. Conf. on Advanced Intelligent Mechatronics (AIM)",
    "aisy": "Adv. Intell. Syst.",
    "akbc": "Automated Knowledge Base Construction",
    "annurevcontrol": "Annual Review of Control, Robotics, and Autonomous Systems",
    "ams": "Autonome Mobile Systeme",
    "amstat": "The American Statistician",
    "ap": "Academic Press",
    "appis": "Applications of Intelligent Systems (APPIS)",
    "applmech": "J. of Applied Mechanics",
    "ar": "Autonomous Robots",
    "arpb": "Annual review of plant biology",
    "arxiv": "arXiv preprint",
    "biosyseng": "Biosystems Engineering",
    "bmcbio": "BMC Bioinformatics",
    "bmvc": "British Machine Vision Conf. (BMVC)",
    "btc-de": "IEEE Bulletin of the Tech. Committee on Data Engineering",
    "case": "Intl. Conf. on Automation Science and Engineering (CASE)",
    "cacm": "Communications of the ACM",
    "ccvw": "Croation Computer Vision Workshop (CCVW)",
    "cdc": "IEEE Conf. on Decision and Control (CDC)",
    "cea": "Computers and Electronics in Agriculture",
    "chap": "Chapman and Hall",
    "cigr": "Intl. Conf. of Agricultural Engineering (CIGR)",
    "cira": "IEEE Intl. Symp. on Computational Intelligence in Robotics and Automation (CIRA)",
    "cob": "Current Opinion in Biotechnology",
    "coc": "College of Computing, Georgia Institute of Technology",
    "cogsys": "Intl. Conf. on Cognitive Systems (CogSys)",
    "compg": "Computers & Graphics",
    "commmag": "IEEE Communications Magazine",
    "corl": "Conf. on Robot Learning (CoRL)",
    "crews": "SPIE Conf. on Reconnaissance and Electronic Warfare System",
    "crv": "Conf. on Computer and Robot Vision (CRV)",
    "cve": "ACM Intl. Conf. on Collaborative Virtual Environments (CVE)",
    "cvgip": "Computer Vision, Graphics, and Image Processing",
    "cviu": "Comput. Vis. Image Underst.",
    "cvpr": "IEEE Conf. on Computer Vision and Pattern Recognition (CVPR)",
    "cvprw": "IEEE/CVF Conf. on Computer Vision and Pattern Recognition Workshops",
    "cvvt": "Intl. Workshop on Computer Vision in Vehicle Technology (CVVT)",
    "dagm": "Symp. of the German Association for Pattern Recognition (DAGM)",
    "dagstuhl": "Dagstuhl Seminar",
    "dars": "Distributed Autonomous Robotic Systems",
    "dgpf": "Conf. of the German Society for Photogrammetry, Remote Sensing and Geoinformation (DGPF)",
    "ecai": "Eur. Conf. on AI (ECAI)",
    "ecc": "European Control Conference",
    "eccv": "European Conf. on Computer Vision (ECCV)",
    "eccvws": "European Conf. on Computer Vision Workshops",
    "ecmr": "European Conf. on Mobile Robots (ECMR)",
    "ecml": "European Conf. on Machine Learning (ECML)",
    "emav": "European Micro Aerial Vehicle Conf.",
    "epb": "Environment and Planning B: Planning and Design",
    "esa": "Expert Systems with Applications",
    "etfa": "IEEE Intl. Conf. on Emerging Technologies Factory Automation (ETFA)",
    "euros": "European Robotics Symp. (EUROS)",
    "fg": "Intl. Conf. on Automatic Face and Gesture Recognition",
    "fns": "Front. Neurosci.",
    "fntr": "Foundations and Trends in Robotics",
    "focs": "Symp. on Foundations of Computer Science",
    "fps": "Frontiers in Plant Science",
    "fr": "Field Robotics",
    "fsr": "Field and Service Robotics (FSR)",
    "fusion": "Intl. Conf. on Information Fusion (FUSION)",
    "gcpr": "German Conf. on Pattern Recognition (GCPR)",
    "gecco": "Conf. on Genetic and Evolutionary Computation (GECCO)",
    "gmip": "CVGIP:Graphical Models and Image Processing",
    "gnc": "AIAA Guidance, Navigation, and Control Conference",
    "grsl": "IEEE Geoscience and Remote Sensing Letters",
    "hri": "Intl. Conf. on Human-Robot Interaction (HRI)",
    "humanoids": "IEEE Intl. Conf. on Humanoid Robots",
    "iapr": "Intl. Conf. on Image Processing A",
    "ias": "Intl. Conf. on Intelligent Autonomous Systems (IAS)",
    "icannml": "International Conference on Artificial Neural Networks and Machine Learning",
    "icar": "Intl. Conf. on Advanced Robotics (ICAR)",
    "icarcv": "Intl. Conf. on Control, Automation, Robotics and Vision (ICARCV)",
    "icassp": "Intl. Conf. Acoust., Speech, and Signal Processing (ICASSP)",
    "icces": "Intl. Conf. on Computer Engineering Systems (ICCES)",
    "iccp": "IEEE Int. Conf. Comput. Photography (ICCP)",
    "iccv": "Intl. Conf. on Computer Vision (ICCV)",
    "iccvw": "{Proceedings of the International Conference on Computer Vision Workshops ({ICCVW})}",
    "iccvws": "Intl. Conf. on Computer Vision Workshops",
    "icfp": "Intl. Conf. on Functional Programming (ICFP)",
    "icr": "Intl. Conf. on Interactive Collaborative Robotics (ICR)",
    "iciap": "Intl. Conf. on Image Analysis and Processing (ICIAP)",
    "icif": "Intl. Conf. on Information Fusion",
    "icip": "Intl. Conf. on Image Processing (ICIP)",
    "icitcs": "Intl. Conf. on Information Technology and Contemporary Sports (TCS)",
    "icinco": "Intl. Conf. on Informatics in Control (ICINCO)",
    "iclr": "Intl. Conf. on Learning Representations (ICLR)",
    "icmcr": "Intl. Conf. on Mechatronics, Control and Robotics (ICMCR)",
    "icme": "IEEE Intl. Conf. on Multimedia and Expo (ICME)",
    "icml": "Intl. Conf. on Machine Learning (ICML)",
    "icmla": "IEEE Intl. Conf. on Machine Learning and Applications (ICMLA)",
    "icpr": "Intl. Conf. on Pattern Recognition (ICPR)",
    "icra": "IEEE Intl. Conf. on Robotics and Automation (ICRA)",
    "ictai": "Intl. Conf. on Tools with Artificial Intelligence (ICTAI)",
    "icuas": "Intl. Conf. on Unmanned Aircraft Systems (ICUAS)",
    "icvs": "Int. Conf. Comput. Vis. Syst. (ICVS)",
    "ieee": "Proc. IEEE",
    "ieeepress": "IEEE Computer Society Press",
    "ifac": "IFAC-PapersOnLine",
    "ijabe": "Intl. J. of Agricultural and Biological Engineering",
    "ijars": "Intl. J. of Advanced Robotic Systems",
    "ijcai": "Intl. Joint Conf. on AI (IJCAI)",
    "ijcars": "Intl. Journal of Computer Assisted Radiology and Surgery (IJCARS)",
    "ijcnlp": "Intl. Joint Conf. on Natural Language Processing",
    "ijcnn": "Int. Joint Conf. Neural Netw. (IJCNN)",
    "ijcv": "Intl. J. of Computer Vision",
    "ijf": "Intl. Journal of Forecasting (IJF)",
    "ijgi": "Intl. J. of Geo-Information",
    "ijhr": "The Intl. J. of Humanoid Robotics (IJHR)",
    "ijrr": "Intl. J. of Robotics Research",
    "ijrs": "Intl. J. of Remote Sensing",
    "ijsip": "Intl. J. of Signal Processing, Image Processing and Pattern Recognition",
    "imvip": "Irish Machine Vision and Image Processing Conf. (IMVIP)",
    "iotj": "IEEE Internet of Things Journal",
    "ipsn": "Intl. Sym. on Information Processing in Sensor Networks (IPSN)",
    "iros": "IEEE/RSJ Intl. Conf. on Intelligent Robots and Systems (IROS)",
    "irosws": "IEEE/RSJ Intl. Conf. on Intelligent Robots and Systems Workshops",
    "isar": "IEEE and ACM Intl. Sym. on Augmented Reality (ISAR)",
    "iser": "Intl. Sym. on Experimental Robotics (ISER)",
    "isic": "Intl. Symp. on Intelligent Control (ISIC)",
    "ismar": "IEEE and ACM Intl. Sym. on Mixed and Augmented Reality (ISMAR)",
    "ismr": "Intl. Sym. on Mixed Reality (ISMR)",
    "isprsannals": "ISPRS Annals of the Photogrammetry, Remote Sensing and Spatial Information Sciences",
    "isprsarchives": "ISPRS Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences",
    "isrr": "Intl. Symp. of Robotics Research (ISRR)",
    "isscc": "IEEE Int. Solid-State Circuits Conf. (ISSCC)",
    "iswc": "IEEE Intl. Sym. on Wearable Computers (ISWC)",
    "itsc": "IEEE Intl. Conf. on Intelligent Transportation Systems (ITSC)",
    "iuw": "DARPA Image Understanding Workshop (IUW)",
    "iv": "IEEE Intelligent Vehicles Symposium (IV)",
    "ivc": "Image and Vision Computing",
    "ivis": "IEEE Visualization",
    "jacm": "J. of the ACM",
    "jaer": "J. of Agricultural Engineering Research",
    "jair": "J. of Artificial Intelligence Research",
    "jasa": "J. of the American Statistical Association",
    "jbe": "ASME J. of Basic Engineering",
    "jeplmc": "J. of Experimental Psychology: Learning,Memory, & Cognition",
    "jfr": "J. of Field Robotics",
    "jif": "Information Fusion",
    "jirs": "J. of Intelligent and Robotic Systems",
    "jmiv": "J. of Mathematical Imaging and Vision",
    "jmlr": "J. of Machine Learning Research",
    "jmp": "Mathematical Programming",
    "joe": "IEEE J. of Oceanic Engineering",
    "josaa": "J. of the Optical Society of America A",
    "jpdc": "J. of Parallel and Distributed Computing",
    "jprs": "ISPRS J. of Photogrammetry and Remote Sensing (JPRS)",
    "jra": "IEEE J. of Robotics and Automation",
    "jras": "J. on Robotics and Autonomous Systems (RAS)",
    "jsiam": "J. Soc. Indust. Appl. Math.",
    "jvcir": "J. of Visual Communication and Image Representation",
    "kdd": "Intl. Conf. Knowledge Discovery and Data Mining (KDD)",
    "kluwer": "Kluwer",
    "lsno": "Large-Scale Nonlinear Optimization",
    "m2rsm": "IEEE Intl. Workshop on Multi-Platform/Multi-Sensor Remote Sensing and Mapping",
    "mcg": "Intl. Conf. on Machine Control and Guidance (MCG)",
    "med": "Mediterranean Conference on Control and Automation",
    "mia": "Med. Image Anal.",
    "miccai": "Intl. Conf. Medical Image Computing and Computer-Assisted Intervention (MICCAI)",
    "mirage": "Intl. Conf. on Computer Vision/Computer Graphics Collaboration Techniques and Applications (MIRAGE)",
    "mit": "The MIT press, Cambridge, MA",
    "mg": "Mathematical Geosciences",
    "ml": "Machine learning",
    "mobicom": "{ACM} Intl. Conf. on Mobile Computing and Networking (MobiCom)",
    "mor": "Mathematics of Operations Research",
    "mpc": "Mathematical Programming Computation",
    "msc": "Multiconference on Systems and Control",
    "mva": "IAPR Conf. on Machine Vision Applications (MVA)",
    "nas": "National Academy of Sciences",
    "neurips": "Advances in Neural Information Processing Systems (NeurIPS)",
    "neuroc": "Neurocomputing",
    "nips": "Conf. Neural Information Processing Systems (NeurIPS)",
    "nipsjournel": "Advances in Neural Information Processing Systems",
    "nipsws": "Neural Information Processing Systems Workshops",
    "npl": "Neural Processing Letters",
    "nrlq": "Naval research logistics quarterly",
    "oceans": "OCEANS MTS/IEEE Conf. and Exhibition",
    "optimmethodsoftw": "Optim. Methods. Softw.",
    "omnn": "Optical Memory and Neural Networks",
    "paa": "Pattern Analysis and Applications",
    "pami": "IEEE Trans. Pattern Anal. Machine Intell.",
    "pbg": "Symposium on Point-Based Graphics (PBG)",
    "pagri": "Precision Agriculture",
    "pcv": "ISPRS Conf. on Photogrammeric Computer Vision (PCV)",
    "pers": "Photogrammetric Engineering and Remote Sensing (PE&RS)",
    "pfg": "Photogrammetrie -- Fernerkundung -- Geoinformation (PFG)",
    "phowo": "Photogrammetric Week (PhoWo)",
    "pia": "ISPRS Conf. on Photogrammeric Image Analysis (PIA)",
    "plans": "IEEE/ION Position Location and Navigation System (PLANS) Conference",
    "plantphysiology": "Plant Physiology",
    "plosone": "PLOS ONE",
    "pr": "Pattern Recognition",
    "prl": "Pattern Recognition Letters",
    "ral": "IEEE Robotics and Automation Letters",
    "ram": "IEEE Robotics and Automation Magazine",
    "ras": "Robotics and Autonomous Systems",
    "rita": "Robot Intelligence Technology and Applications",
    "royalp": "Proceedings of Royal Society of London",
    "rs": "Remote Sensing",
    "rss": "Robotics: Science and Systems (RSS)",
    "rssws": "Robotics: Science and Systems Workshop",
    "rvs95": "Representation of Visual Scenes",
    "scia": "Scandinavian Conf. on Image Analysis",
    "scirob": "Science Robotics",
    "scl": "Systems & Control Letters",
    "sensors": "IEEE Sensors",
    "siam": "SIAM J. on Algebraic and Discrete Methods",
    "sice": "Annual Conf. of the Society of Instrument and Control Engineers (SICE)",
    "sii": "Intl. Symp. on System Integration (SII)",
    "siggraph": "Intl. Conf. on Computer Graphics and Interactive Techniques (SIGGRAPH)",
    "siggraph-asia": "Intl. Conf. on Computer Graphics and Interactive Techniques (SIGGRAPH) Asia",
    "sigir": "ACM Special Interest Group on Information Retrieval",
    "siopt": "SIAM J. Optim.",
    "sirev": "SIAM Review (SIREV)",
    "snowbird": "Snowbird Learning Workshop",
    "soave": "Workshop on Self-Organization of AdaptiVE behavior (SOAVE)",
    "soda": "Annual ACM-SIAM Symp. on Discrete Algorithms (SODA)",
    "spie": "Intl. Soc. Opt. Eng. (SPIE)",
    "spiesdvrs": "SPIE Stereoscopic Displays and Virtual Reality Systems",
    "spiev": "SPIE Videometrics",
    "springer": "Springer Verlag",
    "springerstaradvanced": "STAR Springer Tracts in Advanced Robotics",
    "ssc": "IEEE J. Solid-State Circuits",
    "ssns": "Sensors, Systems, and Next-Generation Satellites",
    "ssrr": "IEEE Intl. Conf. on Safety, Security and Rescue Robotics (SSRR)",
    "stoc": "ACM Symp. on Theory of Computing (STOC)",
    "sysj": "IBM Systems Journal",
    "tac": "IEEE Trans. on Automatic Control",
    "taes": "IEEE Trans. Aerosp. Electron. Syst.",
    "tase": "IEEE Trans. on Automation Science and Engineering",
    "talg": "ACM Trans. on Algorithms (TALG)",
    "tarj": "The Australian Rangeland Journal",
    "tas": "IEEE Trans. Aerosp.",
    "tassp": "IEEE Trans. Acoust., Speech, Signal Processing",
    "tbcas": "IEEE Trans. Biomed. Circuits Syst.",
    "tc": "IEEE Trans. on Cybernetics",
    "tcomp": "IEEE Trans. Computers",
    "tcds": "IEEE Trans. on Cognitive and Developmental Systems ",
    "tcs": "Theoretical Computer Science",
    "tcsii": "IEEE Trans. Circuits Syst. {II} (TCSII)",
    "tcsvt": "IEEE Trans. on Circuits and Systems for Video Technology (TCSVT)",
    "tfr": "IEEE Trans. Field Robotics",
    "tgrs": "IEEE Trans. on Geoscience and Remote Sensing",
    "tim": "IEEE Trans. Instrum. Meas.",
    "tip": "IEEE Trans. on Image Processing",
    "tist": "{ACM} Trans. Intell. Syst. Technol.",
    "tit": "IEEE Trans. Inform. Theory",
    "titac": "IEEE Trans. Automat. Contr.",
    "tits": "IEEE Trans. on Intelligent Transportation Systems (TITS)",
    "titsmag": "IEEE Trans. on Intelligent Transportation Systems Magazine",
    "tiv": "IEEE Trans. on Intelligent Vehicles (TIV)",
    "tkdd": "{ACM} Trans. Knowl. Discov. Data",
    "tmi": "IEEE Trans. Med. Imaging",
    "tmlr": "Trans. on Machine Learning Research (TMLR)",
    "tmm": "IEEE Transactions on Multimedia",
    "tnnls": "IEEE Trans. Neural Netw. Learn. Syst.",
    "toc": "IEEE Trans. on Cybernetics",
    "toe": "IEEE Trans. on Education",
    "tog": "ACM Trans. on Graphics (TOG)",
    "tpami": "IEEE Trans. Pattern Anal. Machine Intell.",
    "tra": "IEEE Trans. Robot. Automat.",
    "tro": "IEEE Trans. Robotics",
    "tsmc": "IEEE Trans. on Systems, Man, and Cybernetics",
    "tsp": "IEEE Trans. Signal Processing",
    "tvcg": "IEEE Trans. Vis. Comput. Graph.",
    "uai": "Conf. on Uncertainty in Artificial Intelligence (UAI)",
    "uavg": "Intl. Conf. on Unmanned Aerial Vehicles in Geomatics",
    "uust": "Intl. Symp. on Unmanned Untethered Submersible Technology",
    "ur": "Intl. Conf. on Ubiquitous Robots (UR)",
    "vc": "The Visual Computer (VC)",
    "vldb": "Intl. Conf. on Very Large Database (VLDB)",
    "visapp": "Intl. Conf. of Computer Vision Theory and Applications (VISAPP)",
    "vmv": "Vision, Modeling, Visualization (VMV)",
    "wacv": "IEEE/CVF Winter Conf. on Applications of Computer Vision (WACV)",
    "wafr": "Intl. Workshop on the Algorithmic Foundations of Robotics (WAFR)",
    "wcica": "World Congress on Intelligent Control and Automation",
    "wiley": "John Wiley & Sons, New York, NY",
    "wsdm": "Intl. Conf. on Web Search and Data Mining",
}
